### ISSUE TITLE
Matching jwt token against a regex

### ISSUE THREAD

**Issue by sohailalam2** [brianloveswords/node-jws#38] opened 2016-01-14 12:30 UTC
Hey Guys,

We are facing some issues with the jsonwebtoken library when we create our own token following the JWT standards (using C language). Unfortunately the official C library doesnt compile well in our Windows environment. 

After debugging for days we came to the conclusion that the regex used in the **jws** library **verify-stream.js** file does not allow for equals sign (=), hence the regex validation fails.

Currently the regex looks like as follow - 

```js
const JWS_REGEX = /^[a-zA-Z0-9\-_]+?\.[a-zA-Z0-9\-_]+?\.([a-zA-Z0-9\-_]+)?$/;
```

Suggested change is to include the (=) sign as well - 

```js
const JWS_REGEX = "^[A-Za-z0-9-_=]+\.[A-Za-z0-9-_=]+\.?[A-Za-z0-9-_.+/=]*$";
```

Thanks

**Comment by omsmith** [comment] 2016-01-14 12:52
Dupe of #22

Sorry, but your C implementation is not following the spec.

The JOSE set of standards uses "URL safe Base64".

Replace `+` with `-`, `/` with `_`, and remove all padding (`=`).

**Closed by omsmith** 2016-01-14 12:52 UTC

**Comment by sohailalam2** [comment] 2016-01-14 16:20
@jfromaniello, @omsmith Thank you for the quick response. We will make the required chanes as suggested.
